- src/main/java/gifterz/textme/domain/entity/BaseEntity.java
- src/main/java/gifterz/textme/domain/user/entity/Major.java
- src/main/java/gifterz/textme/domain/user/entity/User.java
> Refactor: Major 엔티티 추가

- src/main/java/gifterz/textme/domain/letter/controller/LetterController.java
- src/main/java/gifterz/textme/domain/letter/service/LetterService.java
- src/main/java/gifterz/textme/domain/user/repository/UserRepository.java
> Refactor: 사용자는 모든 게시물을 볼 수 있다.

- src/main/java/gifterz/textme/domain/letter/service/LetterService.java
> 편지에서 단과대학 정보를 볼 수 있게 변경

- src/main/java/gifterz/textme/domain/entity/BaseEntity.java
- src/main/java/gifterz/textme/domain/letter/controller/LetterController.java
- src/main/java/gifterz/textme/domain/letter/service/LetterService.java
- src/main/java/gifterz/textme/domain/user/entity/Major.java
- src/main/java/gifterz/textme/domain/user/entity/User.java
- src/main/java/gifterz/textme/domain/user/repository/UserRepository.java
- 필요없는 Jpa 인터페이스 삭제 (findByUser)
- Letter와 User가 연관관계를 형성해 Letter 내 User 필드가 있기에 getter 메서드만 사용하여 User 가져옴.
> Refactor: find letter

- src/main/java/gifterz/textme/domain/oauth/infra/dku/dto/AuthCodeRequest.java
- src/main/java/gifterz/textme/domain/oauth/util/OauthMemberClientMapper.java
작업 사항
- DKU 인증 코드 요청 시 codeChallenge, codeChallengeMethod 체크 로직을 인증 코드 요청 DTO에 추가
- 지원하지 않는 로그인 타입일 때 반환하는 에러 메세지 변경
> Refactor: DTM-9-add-oauth

- .gitignore
- build.gradle
- src/main/java/gifterz/textme/domain/oauth/infra/dku/controller/DkuApi.java
- src/main/java/gifterz/textme/domain/oauth/infra/dku/util/DkuAuthCodeRequestUrlProvider.java
- src/main/java/gifterz/textme/domain/oauth/infra/kakao/controller/KakaoApi.java
- src/main/java/gifterz/textme/domain/oauth/infra/kakao/util/KakaoAuthCodeRequestUrlProvider.java
- src/main/resources/application.yml
Issue
#15 
작업 사항
OAuth URI 환경변수로 주입
+++)
배포할 이미지 변경
> Refactor: dtm-15-conceal-uri

- src/main/java/gifterz/textme/domain/oauth/config/HttpInterfaceConfig.java
- src/main/java/gifterz/textme/domain/oauth/infra/dku/controller/DkuApi.java
- src/main/java/gifterz/textme/domain/oauth/infra/dku/dto/DkuMemberResponse.java
- src/main/java/gifterz/textme/domain/oauth/infra/kakao/controller/KakaoApi.java
- src/main/resources/application.yml
Issue
https://github.com/GIFTERZ/dankook-text-me-server/issues/15
작업 사항
DKU OAuth base-url만 환경변수로 주입 후, 뒤 path는 명시
+++)
DKU 멤버 조회 Response DTO 내 name -> username으로 리팩토링
> Refactor: DTM-15-conceal-uri

- src/main/java/gifterz/textme/domain/oauth/config/HttpInterfaceConfig.java
> fix: DKU BASE URI 하이픈 수정

- build.gradle
- src/main/java/gifterz/textme/domain/oauth/infra/dku/dto/DkuMemberResponse.java
- src/main/java/gifterz/textme/domain/oauth/infra/dku/service/DkuMemberClient.java
- src/main/java/gifterz/textme/domain/oauth/service/OauthService.java
- src/main/java/gifterz/textme/domain/user/dto/response/LoginResponse.java
- src/main/java/gifterz/textme/domain/user/entity/User.java
- src/main/java/gifterz/textme/domain/user/repository/MajorRepository.java
related #21 
- User 엔티티에 gender 필드 추가
- 소셜 회원가입 시 사용자의 성별도 가져오도록 변경
- User와 Major 사이 제약조건 제거
- User와 Major n:1 관계 설정
- 안쓰는 메서드 제거
- compile 속성 -parameter 추가 (@RequestParam 사용 시 모두 직접 명시하지 않기 위함)
> Refactor: DTM-21-modify-user

- src/main/java/gifterz/textme/domain/letter/controller/EventLetterController.java
- src/main/java/gifterz/textme/domain/letter/dto/request/EventLetterRequest.java
- src/main/java/gifterz/textme/domain/letter/dto/request/SenderInfo.java
- src/main/java/gifterz/textme/domain/letter/dto/request/SlowLetterWithAddressRequest.java
- src/main/java/gifterz/textme/domain/letter/dto/request/SlowLetterWithEmailRequest.java
- src/main/java/gifterz/textme/domain/letter/dto/request/Target.java
- src/main/java/gifterz/textme/domain/letter/entity/EventLetter.java
- src/main/java/gifterz/textme/domain/letter/repository/EventLetterRepository.java
- src/main/java/gifterz/textme/domain/letter/service/EventLetterService.java
- src/main/java/gifterz/textme/global/config/WebConfig.java
related #30 
- 이벤트 전송에 필요한 EventLetter와 관련한 entity, repo, service, controller 추가
- 이벤트 편지 전송 DTO 추가
- SenderInfo VO 리팩토링(기존 imageUrl 필드 제거 및 contactInfo 추가)
- Target VO 추가(편지 내용 관련 VO로 imageUrl과 contents 있음)
- cors mapping origin 변경
> Feature:DTM-30-send-event-letter

- src/main/java/gifterz/textme/domain/letter/controller/LetterController.java
- src/main/java/gifterz/textme/domain/letter/entity/Letter.java
- src/main/java/gifterz/textme/domain/letter/service/LetterService.java
- sendSlowLetterWithEmail 메서드 인자 변경
- Letter 내 AllArgsConstructor어노테이션 제거 및 리포맷
> Refactor: SlowLetter 전송 인자 변경

- src/main/java/gifterz/textme/domain/oauth/controller/OauthController.java
- src/main/java/gifterz/textme/domain/oauth/repository/OauthMemberRepository.java
- src/main/java/gifterz/textme/domain/oauth/service/OauthService.java
relate #34 
- HttpServletResponse.sendRedirect() -> RedirectView 사용으로 변경
- oauthMember save 조건 수정(기존 oauthId를 사용해 oauthMember 존재 여부 파악 했는데 동일한 oauthId를 갖는 사용자가 있을 수 있기 때문에 User를 사용해 존재 여부 파악함, user와 oauthMember는 1:1 보장)
> refactor: HttpServletResponse.sendRedirect() -> RedirectView 사용으로 변경

- src/main/java/gifterz/textme/domain/letter/controller/EventLetterController.java
- src/main/java/gifterz/textme/domain/letter/dto/response/AllEventLetterResponse.java
- src/main/java/gifterz/textme/domain/letter/repository/EventLetterRepository.java
- src/main/java/gifterz/textme/domain/letter/service/EventLetterService.java
related #25 
- men/women 에 따라 남자/여자로 필터링 된 eventLetter를 조회
- status가 active인 데이터만 조회
> Feature: DTM-25-filter-by-gender

- src/main/java/gifterz/textme/domain/letter/entity/EventLetter.java
- src/main/java/gifterz/textme/domain/letter/repository/EventLetterRepository.java
- src/main/java/gifterz/textme/domain/letter/service/EventLetterService.java
- src/main/java/gifterz/textme/global/config/WebConfig.java
- src/test/java/gifterz/textme/domain/letter/service/EventLetterServiceTest.java
Reverts GIFTERZ/dankook-text-me-server#39
> Revert "refactor: optimistic -> pessimistic lock 사용으로 변경"

- src/main/java/gifterz/textme/domain/entity/StatusType.java
- src/main/java/gifterz/textme/domain/letter/controller/EventLetterController.java
- src/main/java/gifterz/textme/domain/letter/entity/EventLetter.java
- src/main/java/gifterz/textme/domain/letter/service/EventLetterService.java
related #37 
- status에 PENDING 추가(신고 받은 후 관리자 승인 대기 중인 상태)
- 이벤트편지 신고할 경우 status를 PENDING으로 변경
> Feature: DTM-37-report-event-letter

- src/main/java/gifterz/textme/domain/letter/controller/EventLetterController.java
이벤트편지 성별 필터 조회 API에 유저만 접근하도록 UserAuth 추가
> fix: eventLetter 성별 필터 조회 API에 UserAuth 추가

- src/main/java/gifterz/textme/domain/entity/StatusType.java
- src/main/java/gifterz/textme/domain/letter/controller/EventLetterController.java
- src/main/java/gifterz/textme/domain/letter/dto/response/AdminEventLetterResponse.java
- src/main/java/gifterz/textme/domain/letter/repository/EventLetterRepository.java
- src/main/java/gifterz/textme/domain/letter/service/EventLetterService.java
related #47 
status(nullable)에 따른 이벤트편지 조회 API 생성(관리자만 조회 가능)
> Feature: DTM-47-admin-view-letters

- src/main/java/gifterz/textme/global/auth/aspect/AuthTypeCheckAspect.java
- src/main/java/gifterz/textme/global/auth/aspect/RoleCheckAspect.java
related #56 
- 권한 확인할 때, JwtAuthentication 없을 시 예외처리
> Refactor: DTM-56-split-check-authority

- src/main/java/gifterz/textme/domain/letter/controller/EventLetterController.java
- src/main/java/gifterz/textme/domain/letter/dto/response/EventLetterResponse.java
- src/main/java/gifterz/textme/domain/letter/dto/response/WhoseEventLetterResponse.java
- src/main/java/gifterz/textme/domain/letter/exception/AlreadyPostedUserException.java
- src/main/java/gifterz/textme/domain/letter/repository/EventLetterRepository.java
- src/main/java/gifterz/textme/domain/letter/service/EventLetterService.java
related #30
- sendLetter 시 이미 작성한 편지 있는지 확인 validation 추가
- findLetter 반환형에 자신이 작성한 편지인지, 타인이 작성한 편지인지 확인 필드 추가
> Refactor: 편지 전송 시 자신이 보낸 편지가 있는지 확인 및 validation 추가

- src/main/java/gifterz/textme/domain/letter/controller/EventLetterController.java
- src/main/java/gifterz/textme/domain/letter/dto/response/AllEventLetterResponse.java
- src/main/java/gifterz/textme/domain/letter/entity/EventLetter.java
- src/main/java/gifterz/textme/domain/letter/repository/EventLetterRepository.java
- src/main/java/gifterz/textme/domain/letter/service/EventLetterService.java
- src/main/java/gifterz/textme/domain/user/entity/User.java
related #62 
- 이벤트 편지 조회할 때 성별 -> 성별 + 연락처 유무 필터링 하도록 변경
- isMine 필드 포함하여 응답 반환
> Feature: DTM-62-filter-by-contact-info

- src/main/java/gifterz/textme/domain/letter/entity/Category.java
- src/main/java/gifterz/textme/domain/letter/entity/PrizeLetter.java
- src/main/java/gifterz/textme/domain/letter/entity/PrizeLetterVO.java
related #74 
- PrizeLetter 엔티티 추가
- PrizeLetter VO 추가
- Category Enum 추가
> Feature: DTM-74-add-prize-letter

- build.gradle
- src/main/java/gifterz/textme/domain/letter/controller/PrizeLetterController.java
- src/main/java/gifterz/textme/domain/letter/dto/request/PrizeLetterRequest.java
- src/main/java/gifterz/textme/domain/letter/repository/PrizeLetterRepository.java
- src/main/java/gifterz/textme/domain/letter/service/PrizeLetterService.java
- src/main/java/gifterz/textme/error/ErrorCode.java
- src/main/java/gifterz/textme/global/utils/TSIDUtils.java
- src/main/java/gifterz/textme/s3Proxy/FileUploadController.java
- src/main/java/gifterz/textme/s3Proxy/FileUtils.java
- src/main/java/gifterz/textme/s3Proxy/S3Service.java
- src/main/java/gifterz/textme/s3Proxy/exception/FileTooLargeException.java
- src/main/java/gifterz/textme/s3Proxy/exception/InvalidFileException.java
- src/main/java/gifterz/textme/s3Proxy/exception/ResizeFileException.java
- src/main/java/gifterz/textme/s3Proxy/exception/UploadFileException.java
- src/main/resources/application.yml
related #75 
- PrizeLetter 작성 핸들러 추가
- S3Service 내 역할 과다 -> FileUtils 추가하여 로직 이동(resize, validation check, get format name)
- S3 업로드 오브젝트 명 기존 UUID + 파일명 -> TSID로 변경하여 효율 향상
> Feature: DTM-75-send-prize-letter

- src/main/java/gifterz/textme/domain/letter/controller/PrizeLetterController.java
- src/main/java/gifterz/textme/domain/letter/dto/response/AllPrizeLettersResponse.java
- src/main/java/gifterz/textme/domain/letter/service/PrizeLetterService.java
related #76 
- PrizeLetterController 내 getPrizeLetters 핸들러 추가
- AllPrizeLettersResponse DTO 추가
- PrizeLetterService 내 getPrizeLetters 로직 추가
> Feature: DTM-76-get-all-prize-letter

- src/main/java/gifterz/textme/domain/letter/controller/PrizeLetterController.java
- src/main/java/gifterz/textme/domain/letter/dto/response/PrizeLetterResponse.java
- src/main/java/gifterz/textme/domain/letter/exception/PrizeLetterNotFoundException.java
- src/main/java/gifterz/textme/domain/letter/service/PrizeLetterService.java
- src/main/java/gifterz/textme/error/ApplicationExceptionHandler.java
- src/main/java/gifterz/textme/global/auth/aspect/AuthTypeCheckAspect.java
- src/main/java/gifterz/textme/global/auth/aspect/RoleCheckAspect.java
related #77 
- PrizeLetter id를 pathVariable로 입력받아 조회하는 핸들러 추가(관리자 권한)
- Common Exception 발생 시 해당 Exception 고유 메세지 출력되도록 핸들러 로직 변경
- Auth Check 로직 내 for 문에서 불필요한 throw 구문 제거
> Feature: DTM-77-get-one-prize-letter

- build.gradle
- src/main/java/gifterz/textme/domain/letter/controller/PrizeLetterController.java
- src/main/java/gifterz/textme/global/config/WebSecurityConfig.java
- src/main/resources/application.yml
related #83 
- Grafana와 Prometheus 사용 위한 설정 추가
- jib 최소, 최대 힙 크기 변경
- PrizeLetter 전체 조회 권한 Admin -> Dku로 변경
> Feature: DTM-83-add-monitoring
